const data = {
    this: {
        _v: "<type 'PythonListPlugIn'>",
        AfterBarItemClick: {
            _v: "AfterBarItemClick(点击后触发)\n和 BarItemClick 最大的区别是，BarItemClick可以做e.Cancel，可以取消点击事件的后续执行，取消之后，其他插件在AfterBarItemClick里面实现的功能就不再执行",
        },
        // AfterBatchCopyData: {},
        // AfterBindData: {},
        // AfterButtonClick: {},
        // AfterConfirmOperation: {},
        // AfterCopyRow: {},
        // AfterCreateFilterField: {},
        // AfterCreateModelData: {},
        // AfterCreateNewData: {},
        // AfterCreateNewEntryRow: {},
        // AfterCreateSqlBuilderParameter: {},
        // AfterDeleteEntry: {},
        // AfterDeleteRow: {},
        // AfterDoAction: {},
        // AfterDoOperation: {},
        // AfterEntityBlockPasting: {},
        // AfterEntryBarItemClick: {},
        // AfterEntryBatchFill: {},
        // AfterF7Select: {},
        // AfterGetData: {},
        // AfterMenuClick: {},
        // AfterQuickGetData: {},
        // AfterQuickSelect: {},
        // AfterShowCustomerPage: {},
        // AfterShowFlexForm: {},
        // AfterShowForm: {},
        // AfterToolBarItemClick: {},
        // AfterUpdateViewState: {},
        // AuthPermissionBeforeF7Select: {},
        BarItemClick: {
            _v: "BarItemClick(点击时触发)\n和 AfterBarItemClick 最大的区别是，BarItemClick可以做e.Cancel，可以取消点击事件的后续执行，取消之后，其他插件在AfterBarItemClick里面实现的功能就不再执行",
            e: {
                _v: "<type 'BarItemClickEventArgs'>",
                BarItemKey: { _v: "<class 'str'>\ntbPara" },
                Cancel: { _v: "<class 'bool'>" },
                Empty: { _v: "<System.EventArgs object at 0x000000000000003F [System.EventArgs]>" },
                Equals: { _v: "<built-in method Equals of BarItemClickEventArgs object at 0x0000000000000041>" },
                GetHashCode: { _v: "<built-in method GetHashCode of BarItemClickEventArgs object at 0x0000000000000041>" },
                GetType: { _v: "<built-in method GetType of BarItemClickEventArgs object at 0x0000000000000041>" },
                MemberwiseClone: { _v: "<built-in method MemberwiseClone of BarItemClickEventArgs object at 0x0000000000000041>" },
                MenuId: { _v: "<class 'str'>\n20c17963-c45a-45f9-93b9-84790baedf19" },
                ParentKey: { _v: "<class 'str'>\ntbPara" },
                ReferenceEquals: { _v: "<built-in function ReferenceEquals>" },
                ToString: { _v: "<built-in method ToString of BarItemClickEventArgs object at 0x0000000000000041>" },
            }
        },
        // BatchCopyData: {},
        // BeforeBindData: {},
        // BeforeButtonClick: {},
        // BeforeClosed: {},
        // BeforeControlDataBinder: {},
        // BeforeCreateNewEntryRow: {},
        // BeforeCustomEvents: {},
        // BeforeDeleteEntry: {},
        // BeforeDeleteRow: {},
        // BeforeDoAction: {},
        // BeforeDoOperation: {},
        // BeforeEntityExport: {},
        // BeforeEntryBatchFill: {},
        // BeforeEntryRowDataBinder: {},
        // BeforeExportData: {},
        // BeforeExportDataNew: {},
        // BeforeF1Click: {},
        // BeforeF7Select: {},
        // BeforeFilterGridF7Select: {},
        // BeforeFilterSchemeChanged: {},
        // BeforeFlexClosed: {},
        // BeforeFlexSelect: {},
        // BeforeGetDataForTempTableAccess: {},
        // BeforeImportData: {},
        // BeforeMenuClick: {},
        // BeforeNotePrintCommand: {},
        // BeforeOperAfterSelOrg: {},
        // BeforePrintExport: {},
        // BeforeSaveImportData: {},
        // BeforeSetItemValueByNumber: {},
        // BeforeShowImportResultMessage: {},
        // BeforeUpdateValue: {},
        // ButtonClick: {},
        // CellDbClick: {},
        // CellFormat: {},
        // ChangeHTmlTheme: {},
        // Context: {},
        // ContextMenuItemClick: {},
        // CreateFilterEditorControl: {},
        // CreateListHeader: {},
        // CreateNewData: {},
        // CustomEvents: {},
        // DataChanged: {},
        // DataUpdateBeginning: {},
        // DataUpdateEnd: {},
        // Dispose: {},
        // EntityRowClick: {},
        // EntityRowDoubleClick: {},
        // EntryBarItemClick: {},
        // EntryButtonCellClick: {},
        // EntryCellFocued: {},
        // EntryHyperlinkButtonClick: {},
        // Equals: {},
        // FieldEditorFocued: {},
        // FieldLabelClick: {},
        // FireBeforeExportTitle: {},
        // FireEntityBlockPasting: {},
        // FireEntryCheck: {},
        // FireMicroBlogClick: {},
        // FormClosed: {},
        // FormatCellValue: {},
        // GetFormTitle: {},
        // GetHashCode: {},
        // GetTreeViewData: {},
        // GetType: {},
        // GetValidNoteTemplates: {},
        // GetValidNoteTemplatesAll: {},
        // GroupSearchMenuPanelAction: {},
        // HeaderCellClick: {},
        // ImportDataBeforeBindMatchFields: {},
        // ImportDataCollectFailInfo: {},
        // InvokePluginMethod: {},
        // IsLogBasicInfo: {},
        // LanguageChanged: {},
        // ListCreateColumns: {},
        // ListInitialize: {},
        // ListModel: {},
        // ListRowDoubleClick: {},
        ListView: {
            _v: "",
            // AddAction: {},
            // AddChilden: {},
            // AddDataToFormatArry: {},
            // AddLongTaskWatcher: {},
            // AddOrUpdateScheme: {},
            // AfterActionCallback: {},
            // AfterButtonClick: {},
            // AfterConfirm: {},
            // AfterDoLookUpAfterShow: {},
            // AfterDoLookUpBuildParam: {},
            // AfterGetFilterGridF7ShowParameter: {},
            // AfterPrintEvents: {},
            // AfterShowCustomerPage: {},
            // AfterShowUpload: {},
            // ApplyPluginFormatCondition: {},
            // BarItemClick: {},
            // BatchSetItemValueByNumber: {},
            // BeforeCustomEvents: {},
            // BillBusinessInfo: {},
            // BillLayoutInfo: {},
            // BroadcastToOnlineUser: {},
            // BusinessInfo: {},
            // ButtonClick: {},
            // CanDealWithRows: {},
            // ChangeControlLanguage: {},
            // ChangeControlsLangugae: {},
            // ChangeFormInputMode: {},
            // ChangeHTmlTheme: {},
            // ChangeMenuLanguage: {},
            // ClearViewCloseHandler: {},
            // ClientType: {},
            // Close: {},
            // CombinedF7ButtonClick: {},
            // ConcurrentSession: {},
            // ConfirmSaveIfExit: {},
            // Context: {},
            // ContextMenuClick: {},
            // ConvertNail: {},
            // CreateBillShowParameterByPermission: {},
            // CreateColumns: {},
            // CreateDataBinder: {},
            // CreateExportModel: {},
            // CreateModelData: {},
            // CreateSysInnerColumns: {},
            // CurrentLinkRow: {},
            // CurrentPageRowsInfo: {},
            // CurrentSelectedRowInfo: {},
            // CustomEvents: {},
            // DataBinder: {},
            // DefaultUserParameterFormId: {},
            // DeleteScheme: {},
            // DemoLicControl: {},
            // DictFlexLayoutInfo: {},
            // Dispose: {},
            // DoBarItemClick: {},
            // DoButtonClick: {},
            // DoCallBackAction: {},
            // DoKDMessageConcentratorData: {},
            // DoLookUpSetFieldValue: {},
            // DoLookUpSetFieldValueBatch: {},
            // DoPostBack: {},
            // EntityBlockPasting: {},
            // EntityBlockPastingAutoAssign: {},
            // EntityRowClick: {},
            // EntryBarItemClick: {},
            // EntryButtonCellClick: {},
            // EntryButtonCellClickExt: {},
            // EntryCellFocued: {},
            // EntryGotoPage: {},
            // EntryHyperlinkButtonClick: {},
            // EntryRowDoubleClick: {},
            // EntrySetPageSize: {},
            // EntrySwitchPage: {},
            // Equals: {},
            // EventsProxy: {},
            // ExportNotePrint: {},
            // ExportNotePrintWithOption: {},
            // F1Click: {},
            // F1OpenWindow: {},
            // F7ButtonClick: {},
            // FastLocate: {},
            // FieldEditorFocued: {},
            // FieldLabelClick: {},
            // FilterGridF7ButtonClick: {},
            // FilterGridF7IsMultiSelect: {},
            // FilterModel: {},
            // FilterSchemeChanged: {},
            // FireBeforeFilterGridF7Select: {},
            // FlexClearClick: {},
            // FlexClose: {},
            // FlexShowFormAtRow: {},
            // FlexTriggerClick: {},
            // FluidDashBoardChanged: {},
            // FormClosedCallBack: {},
            // FormState: {},
            // FormatCellValue: {},
            // FormatList: {},
            // FormatListRowCondition: {},
            // GetActions: {},
            // GetBarItem: {},
            // GetBarItemEnabled: {},
            // GetBarItemVisible: {},
            // GetBaseDataFormId: {},
            // GetBillRowCount: {},
            // GetCallBackAction: {},
            // GetChildenPageIds: {},
            // GetColumnList: {},
            // GetColumns: {},
            // GetControl: {},
            // GetCustomFormMetaData: {},
            // GetDebugPKValue: {},
            // GetEntryData: {},
            // GetEntryPrintData: {},
            // GetEntryState: {},
            // GetExcelDateFormat: {},
            // GetExcelExportFile: {},
            // GetExportAllRecordsCount: {},
            // GetExportData: {},
            // GetExportTotalBillCount: {},
            // GetFieldEditor: {},
            // GetFieldMkScheme: {},
            // GetFileServerUrl: {},
            // GetFilterLookupList: {},
            // GetFilterLookupList2More: {},
            // GetFilterLookupList2MoreV2: {},
            // GetFilterModel: {},
            // GetFlexFormMetaData: {},
            // GetFlexLayoutInfo: {},
            // GetFormOperation: {},
            // GetFormParamData: {},
            // GetFormTitle: {},
            // GetFormatConditionSysVariableValue: {},
            // GetFormatConditions: {},
            // GetHashCode: {},
            // GetListData: {},
            // GetListHeaderData: {},
            // GetLoadFlexData: {},
            // GetLookupConfig: {},
            // GetLookupList: {},
            // GetLookupList2More: {},
            // GetMainBarItem: {},
            // GetMainMenu: {},
            // GetMenu: {},
            // GetMenus: {},
            // GetMkValue: {},
            // GetOpenParameterForExportEnter: {},
            // GetPageSizeString: {},
            // GetProxyFields: {},
            // GetRowCount: {},
            // GetRows: {},
            // GetSchemeSetting: {},
            // GetSelectedRowsInfo: {},
            // GetService: {},
            // GetSubEntryData: {},
            // GetSummaryRows: {},
            // GetTmpfilePath: {},
            // GetTreeViewData: {},
            // GetType: {},
            // GetUserParaPageSize: {},
            // GetView: {},
            // GetWebServiceData: {},
            // GetYZJPatAuthcode: {},
            // Getauthcode: {},
            // GlobalParameter: {},
            // GroupSearchMenuPanelAction: {},
            // H5RequestInternetHttp: {},
            // HeaderCellClick: {},
            // InitBusinessServiceCaller: {},
            // InitEventProxy: {},
            // InitFilterModel: {},
            // InitFilterParameter: {},
            // InitFlexEventProxy: {},
            // InitFlexPlugIn: {},
            // InitFormState: {},
            // InitListGridControl: {},
            // InitModel: {},
            // InitPlugIn: {},
            // InitStyleManager: {},
            // InitialIsolationOrg: {},
            // Initialize: {},
            // InitializeLookupLikeMatch: {},
            // InitializeParameterObject: {},
            // InsertRows: {},
            // InsertScheme: {},
            // InvokeFieldUpdateService: {},
            // InvokeFormOperation: {},
            // InvokeFormOperation4Wf: {},
            // IsBarItemButtonBusy: {},
            // IsBlankSplitQueryEnabled: {},
            // IsControlLocked: {},
            // IsCurrentRow: {},
            // IsEnabled: {},
            // IsExistPlugIn: {},
            // IsExportCurrencyFormat: {},
            // IsExportDateFormat: {},
            // IsF7focusedQKFilterPanel: {},
            // IsFlexBusy: {},
            // IsFullScreenOnlinePreview: {},
            // IsNeedMk: {},
            // IsRefresh: {},
            // IsRefreshing: {},
            // IsSaveFileColIndex: {},
            // IsVisible: {},
            // LanguageChanged: {},
            // LayoutInfo: {},
            // LicControl: {},
            // ListHeaderData: {},
            // ListViewAddFavorClick: {},
            // ListViewClearClick: {},
            // ListViewClick: {},
            // ListViewPostBackData: {},
            // List_RelatedQueryDetail: {},
            // LoadBillGlobalParameter: {},
            // LoadData: {},
            // LoadDefaultScheme: {},
            // LoadFormParameter: {},
            // LoadFormParameterWithLog: {},
            // LoadMainBarTipsContent: {},
            // LoadPostBackData: {},
            // LoadPostBackDatasIsNull: {},
            // LoadSchemeByOpenParam: {},
            // LoadTipsContent: {},
            // LoadViewContentTips: {},
            // LoadWaterMarkSetting: {},
            // LockBill: {},
            // LockField: {},
            // MainBarItemClick: {},
            // MemberwiseClone: {},
            // MicroBlogButtonClick: {},
            // Model: {},
            // MsgInnerControlEvent: {},
            // NaviOperAction: {},
            // OnClose: {},
            // OnRefresh: {},
            // OnRefreshByFilter: {},
            // OpenParameter: {},
            // PageId: {},
            // ParentFormView: {},
            // PopupWindow: {},
            // PortDataReceived: {},
            // Print: {},
            // ProcessBillValidateResult: {},
            // ProcessViewPageId: {},
            // ProductsPanelAction: {},
            // QueryProgressValue: {},
            // ReferenceEquals: {},
            // Refresh: {},
            // RefreshByFilter: {},
            // RefreshSelectRows: {},
            // RegisterPlugIn: {},
            // ReleaseLongTaskWatcher: {},
            // ReleaseModel: {},
            // RemoveExportModel: {},
            // RemovePlugIn: {},
            // RemoveSelectRows: {},
            // RequestInternetHttpCallBack: {},
            // ResetCustomMetadata: {},
            // ResetState: {},
            // ReturnToParentWindow: {},
            // RowButtonCellClick: {},
            // RowButtonCellClickExt: {},
            // RowCount: {},
            // RowDoubleClick: {},
            // RowExpanding: {},
            // RuleContainer: {},
            // SaveFormParaSetting: {},
            // SaveFormParameter: {},
            // SaveFormParameterWithLog: {},
            // SaveSchemeForExportCenter: {},
            // SaveSchemeForPrintCenter: {},
            // SaveSchemeSetting: {},
            SelectedRowsInfo: {
                _v: "<type 'ListSelectedRowCollection'>\n当前列表上被选中的行记录，复选框勾选的记录集合",
                Add: {},
                Clear: {},
                ClearItems: {},
                Contains: {},
                CopyTo: {},
                Count: {},
                CreateWebParams: {},
                Equals: {},
                GetEntryPrimaryKeyValues: {},
                GetEnumerator: {},
                GetHashCode: {},
                GetPKEntryIdValues: {},
                GetPrimaryKeyValues: {},
                GetRowKeys: {},
                GetType: {},
                IndexOf: {},
                Insert: {},
                InsertItem: {},
                IsReadOnly: {},
                IsSynchronized: {},
                Item: {},
                Items: {},
                MemberwiseClone: {},
                ReferenceEquals: {},
                Remove: {},
                RemoveAt: {},
                RemoveItem: {},
                SetItem: {},
                SyncRoot: {},
                ToString: {},
            },
            // SendAynDynamicFormAction: {},
            // SendDynamicFormAction: {},
            // Session: {},
            // SessionManager: {},
            // SetActions: {},
            // SetAllowBlockPasteAutoAssign: {},
            // SetBusinessInfo: {},
            // SetClientDialogResult: {},
            // SetClientReturnData: {},
            // SetCommonClientPropsAction: {},
            // SetControlState: {},
            // SetControlStatus: {},
            // SetControlsStatus: {},
            // SetEntityFocusRow: {},
            // SetFormTitle: {},
            // SetInnerTitle: {},
            // SetIsEnableColumnHeaderAutoWrap: {},
            // SetItemValueByField: {},
            // SetItemValueByID: {},
            // SetItemValueByIDFromClient: {},
            // SetItemValueByIDFromClientIsText: {},
            // SetItemValueByNumber: {},
            // SetLayoutInfo: {},
            // SetLoadTipsContent: {},
            // SetLookupLikeMatchAction: {},
            // SetMainMenu: {},
            // SetMainMenuAllowHelpAssistant: {},
            // SetModelParameterData: {},
            // SetOtherInfo: {},
            // SetRowFontColor: {},
            // SetSearchKeyword: {},
            // SetViewCloseHandler: {},
            // ShowAllCvpMkData: {},
            // ShowApmMonitorForm: {},
            // ShowCVPAllFieldData: {},
            // ShowCVPFieldData: {},
            // ShowErrMessage: {},
            // ShowFilterGrid: {},
            // ShowFlexForm: {},
            // ShowForm: {},
            // ShowK3Displayer: {},
            // ShowListPrintPageSettingForm: {},
            // ShowMessage: {},
            // ShowNotificationMessage: {},
            // ShowOperateResult: {},
            // ShowStatusBarInfo: {},
            // ShowUpload: {},
            // ShowWarnningMessage: {},
            // StyleManager: {},
            // TabItemSelectedChange: {},
            // TimerElapsed: {},
            // TipsContentInnerNoMoreClick: {},
            // ToString: {},
            // ToolBarItemClick: {},
            // TraceId: {},
            // TreeDragDrop: {},
            // TreeNodeClick: {},
            // TreeNodeDoubleClick: {},
            // TryGetAutoHeaderWrapFromParameterData: {},
            // TryGetBillGlobalParameter: {},
            // TryGetControl: {},
            // TryGetFilterGridF7IsMultiSelect: {},
            // TryGetFormOperation: {},
            // TryGetLookupBillGlobalParameter: {},
            // UpdateCVPFieldData: {},
            // UpdateLongTaskWatcher: {},
            // UpdateModelByParaSetting: {},
            // UpdateValue: {},
            // UpdateView: {},
            // UpdateViewState: {},
            // UserParameterKey: {},
            // ValidateUpdateFieldEnabled: {},
            // ValidateUpdateFieldPermission: {},
            // WriteMkLog: {},
            // _barItemClickPlugin: {},
            // _businessServiceCaller: {},
            // _isEmptyListData: {},
            // _isFirstSeachdata: {},
            // _ruleContainer: {},
            // _saveForDataChanged: {},
            // _serviceProvider: {},
            // _strSetting: {},
            // _styleManager: {},
            // currentPageData: {},
            // currentSelRows: {},
            // dctBillGlobalParameter: {},
            // dctLookUpBillGlobalParameter: {},
            // formatArray: {},
            // initRules: {},
            // oldFocusRow: {},
        },
        // ListViewAddFavorClick: {},
        // ListViewClearClick: {},
        // ListViewClick: {},
        // MemberwiseClone: {},
        Model: {},
        // MsgInnerControlEvent: {},
        // NaviOperAction: {},
        // OnAfterPrint: {},
        // OnAfterPrintExport: {},
        // OnAfterWebApiOperation: {},
        // OnBeforePrintFromPreview: {},
        // OnBeforePrintValidate: {},
        // OnBeforeSendMailService: {},
        // OnBeforeWebApiOperation: {},
        // OnChangeConvertRuleEnumList: {},
        // OnCreateDataBinder: {},
        // OnEntrySum: {},
        // OnFormatRowConditions: {},
        // OnGetConvertRule: {},
        // OnInitialize: {},
        // OnInitializeSendMailService: {},
        // OnInitializeService: {},
        // OnLoad: {},
        // OnPrepareDevPrintData: {},
        // OnPrepareNotePrintData: {},
        // OnPrepareNotePrintQueryParam: {},
        // OnQueryDynamicColumns: {},
        // OnQueryFlexFieldState: {},
        // OnQueryProgressValue: {},
        // OnSetBusinessInfo: {},
        // OnSetLayoutInfo: {},
        // OnShowConvertOpForm: {},
        // OnShowTrackResult: {},
        // OnTargetBillChanged: {},
        // OnTimerElapsed: {},
        // PortDataReceived: {},
        // PreOpenForm: {},
        // PrepareFilterParameter: {},
        // PrepareFuncPermissionDataRule: {},
        // ProductsPanelAction: {},
        // ReferenceEquals: {},
        // ReplaceEntityTable: {},
        // RowExpanding: {},
        // SetContext: {},
        // SetIsLogBasicInfo: {},
        // ShowFlexFormLoad: {},
        // TabItemSelectedChange: {},
        // ToString: {},
        // ToolBarItemClick: {},
        // TreeDragDrop: {},
        // TreeLoadData: {},
        // TreeNodeClick: {},
        // TreeNodeDoubleClick: {},
        // UpdateChartData: {},
        View: {
            ShowErrMessage: {},
            ShowMessage: {},
            ShowWarnningMessage: {},
        },
    }
}

export default data